#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99  # Ðảm bảo chạy sau cùng khi mạng và các dịch vụ khác đã lên hết
STOP=15

start_service() {
    procd_open_instance
    
    # Chỉ định đường dẫn tới file script của bạn
    procd_set_param command /bin/sh "/usr/bin/listen_api.sh"
    
    # Lệnh respawn báo cho procd biết: "Nếu script này chết, hãy tự động bật lại ngay"
    procd_set_param respawn
    
    # Ghi log chuẩn của OpenWrt (để xem bằng lệnh logread)
    procd_set_param stdout 1
    procd_set_param stderr 1
    
    procd_close_instance
}