#!/bin/sh /etc/rc.common

# Chạy ở bước 99 (cuối cùng) sau khi mạng và OpenVPN đã khởi động xong
START=99
USE_PROCD=1
PROG="/usr/bin/watch_ovpn.sh"

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    # BẮT BUỘC CÓ ĐỂ CHÉM ĐỨT ĐUÔI TIẾN TRÌNH CON DO DẤU PIPE (|) GÂY RA
    for pid in $(ps w | grep "[w]atch_ovpn.sh" | awk '{print $1}'); do
        kill -9 "$pid" 2>/dev/null
    done
    killall -9 inotifywait 2>/dev/null
}