#!/bin/sh /etc/rc.common

# Chạy ở bước 99 (cuối cùng) sau khi mạng và OpenVPN đã khởi động xong
START=99
USE_PROCD=1

# Đường dẫn tới script của bạn
PROG="/root/watch_ovpn.sh"

start_service() {
    procd_open_instance
    # Định nghĩa lệnh cần chạy
    procd_set_param command "$PROG"
    
    # Tính năng quan trọng nhất: Tự động chạy lại nếu script bị lỗi/chết
    procd_set_param respawn
    
    # Ghi log output của script vào System Log (logread)
    procd_set_param stdout 1
    procd_set_param stderr 1
    
    procd_close_instance
}